### PR TITLE
Next (doctrine 3, multiple connections)

### PR DESCRIPTION
**Pull request by f3l1x**
Changes:
- fix tests
- fix phpstan
- drop deprecated console commands
- drop deprecated yaml extension

----

Ref: https://github.com/contributte/doctrine-dbal/pull/77

Doctrine upgrades:
- https://github.com/doctrine/orm/blob/2.14.x/UPGRADE.md
- https://github.com/doctrine/dbal/blob/3.5.x/UPGRADE.md

--- 

Demo: https://github.com/contributte/doctrine-skeleton

### CODE REVIEW

**Comment by thorewi** [comment]
Hi, what is needed here to be merged?

**Comment by f3l1x** [comment]
I am finishing tests on my projects.

**Comment by thorewi** [comment]
hi there great work! Is there any docs how to configure more connections? thank you...

**Comment by f3l1x** [comment]
Resolved here: https://github.com/contributte/doctrine-orm/commit/0884b39b3edc4d93dbb1e91e6d2066b50cf372a8

**Pull request merged**
