### PR TITLE
Implemented ResolveTargetEntityListener; Closes #52

### LINKED ISSUE #52: Mapping interface on entity
There are sometimes use-cases when we don't want to use mapping on Entity class in relations, but rather interface (possibly for decoupling reasons). That is why Doctrine supports `ResolveTargetEntityListener` (documentation on: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/cookbook/resolve-target-entity-listener.html). 

It would be nice to have such configuration placed in `config.neon`. Symfony has its own implementation in `config.yml` (as described on https://symfony.com/doc/current/doctrine/resolve_target_entity.html at the bottom of the page)

We managed to do a workaround by placing the following code inside `EntityManagerDecorator`:

```
public function __construct(EntityManagerInterface $wrapped)
	{
		$resolveTargetEntityListener = new ResolveTargetEntityListener();
		$resolveTargetEntityListener->addResolveTargetEntity(UserInterface::class, User::class, []);

		$wrapped->getEventManager()->addEventListener(Events::loadClassMetadata, $resolveTargetEntityListener);
		parent::__construct($wrapped);
	}
```

It's good enough but people still have to remember that.

### PR DESCRIPTION
**Pull request by juniwalk**
I used the same config name as is in Symfony. What do you think?

```neon
# Nettrine \ ORM
orm:
	configuration:
		resolveTargetEntities:
			Nette\Security\IIdentity: App\Entity\User
```

### CODE REVIEW

**Comment by f3l1x** [comment]
I am OK with that, please add some tests to prove it works.

**Comment by juniwalk** [comment]
@f3l1x I tried adding test, but I am not sure that I can do what I did.

**Comment by juniwalk** [comment]
Well I fixed all I could but the last error does not seem to be issue with my changes.

**Comment by f3l1x** [comment]
Excellent. Thank you 👍

**Pull request merged**
